# Generated by Django 4.2.4 on 2023-08-31 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nome_categoria',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='marca',
            old_name='nome_marca',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='nome_produto',
            new_name='nome',
        ),
    ]
